### ISSUE TITLE
MIssing x86 instructions for various binaries

### ISSUE THREAD

**Issue by pgoodman** [trailofbits/remill#127]
The following x86 instructions are missing when trying to lift SQLite3:

 - [x] MINSS_XMMss_MEMss
 - [x] MINSD_XMMsd_MEMsd
 - [x] MAXSS_XMMss_MEMss
 - [x] MAXSD_XMMsd_XMMsd

```
(AMD64_INSTR 419668 6 MINSS_XMMss_MEMss (WRITE_OP (REG_128 XMM0)) (READ_OP (REG_128 XMM0)) (READ_OP (ADDR_64 DWORD RDX + (RAX * 1) + 0x8))))
(AMD64_INSTR 41967a 6 MAXSS_XMMss_MEMss (WRITE_OP (REG_128 XMM0)) (READ_OP (REG_128 XMM0)) (READ_OP (ADDR_64 DWORD RDX + (RAX * 1) + 0xc))))
(AMD64_INSTR 42b491 6 MINSD_XMMsd_MEMsd (WRITE_OP (REG_128 XMM0)) (READ_OP (REG_128 XMM0)) (READ_OP (ADDR_64 DWORD RSP + 0x30))))
(AMD64_INSTR 47bd0b 4 MAXSD_XMMsd_XMMsd (WRITE_OP (REG_128 XMM1)) (READ_OP (REG_128 XMM1)) (READ_OP (REG_128 XMM0)))
```

**Comment by pgoodman** [comment]
Missing for thttpd:
```
(X86_INSTR 81056f5 5 PSLLDQ_XMMdq_IMMb (WRITE_OP (REG_128 XMM2)) (READ_OP (REG_128 XMM2)) (READ_OP (IMM_8 e)))
(X86_INSTR 8105225 5 MOVHPD_XMMsd_MEMq (WRITE_OP (REG_128 XMM2)) (READ_OP (ADDR_32 DWORD (SEGMENT DS_BASE) EDX + 0x8))))
(X86_INSTR 815e7f5 2 FCMOVE_ST0_X87 (WRITE_OP (REG_64 ST0)) (READ_OP (REG_64 ST1)))
```
Lower on the priority, where hyper calls or stop failures may be required:
```
(X86_INSTR 815382d 1 POP_ES_32 (WRITE_OP (REG_16 ES)))
(X86_INSTR 80d5146 3 XGETBV)
(X86_INSTR 80d4a3c 3 XABORT_IMMb (READ_OP (IMM_8 ff)))
(X86_INSTR 80d4aa0 3 XEND)
(X86_INSTR 8148a1b 2 MOV_SEG_GPR16 (WRITE_OP (REG_16 GS)) (READ_OP (REG_16 AX)))
(X86_INSTR 8130601 5 STMXCSR_MEMd (WRITE_OP (ADDR_32 DWORD (SEGMENT SS_BASE) ESP + 0xc))))
(X86_INSTR 8130618 5 LDMXCSR_MEMd (READ_OP (ADDR_32 DWORD (SEGMENT SS_BASE) ESP + 0xc))))
```

**Comment by mike-myers-tob** [comment]
MINSS passes the tests I wrote for it; VMINSS does not but I will work on MINSD, MAXSS, and MAXSD first since they are trivially different from MINSS.

**Comment by mike-myers-tob** [comment]
MAXSS and VMAXSS should be working now in the latest commit.

**Comment by pgoodman** [comment]
Nice.

**Comment by pgoodman** [comment]
Needed for httpd:

 - [ ] `(AMD64 b2ff8 3 (BYTES 0f 14 c9) UNPCKLPS_XMMps_XMMq (WRITE_OP (REG_128 XMM1)) (READ_OP (REG_128 XMM1)) (READ_OP (REG_128 XMM1)))`
 - [ ] `(AMD64 b300e 4 (BYTES 66 0f 14 c0) UNPCKLPD_XMMpd_XMMq (WRITE_OP (REG_128 XMM0)) (READ_OP (REG_128 XMM0)) (READ_OP (REG_128 XMM0)))`
 - [ ] `(AMD64 b3016 4 (BYTES f3 0f 51 d0) SQRTSS_XMMss_XMMss (WRITE_OP (REG_128 XMM2)) (READ_OP (REG_128 XMM0)))`
 - [ ] `(AMD64 b23a2 4 (BYTES f2 0f 12 c1) MOVDDUP_XMMdq_XMMq (WRITE_OP (REG_128 XMM0)) (READ_OP (REG_128 XMM1)))`

**Comment by mike-myers-tob** [comment]
All right, MINSD, VMINSD, MAXSD, and VMAXSD should be working in the most recent commit.

I'll start taking a look at UNPCKLPS_XMMps_XMMq, UNPCKLPD_XMMpd_XMMq, SQRTSS_XMMss_XMMss, and MOVDDUP_XMMdq_XMMq.

**Comment by mike-myers-tob** [comment]
UNPCKLPS, VUNPCKLPS, UNPCKLPD, VUNPCKLPD, MOVDDUP, VMOVDDUP all done. I did 128-bit AVX variants but I didn't do the 256-bit AVX, instead just trying to get the base functionality done.

**Comment by pgoodman** [comment]
- [ ] `(X86 410bd5 5 (BYTES f2 0f 70 db 00) PSHUFLW_XMMdq_XMMdq_IMMb (WRITE_OP (REG_128 XMM3)) (READ_OP (REG_128 XMM3)) (READ_OP (IMM_8 0)))`
 - [ ] `(X86 410bda 3 (BYTES 0f 16 db) MOVLHPS_XMMq_XMMq (WRITE_OP (REG_128 XMM3)) (READ_OP (REG_128 XMM3)))`
 - [ ] `(X86 40e35b 3 (BYTES d9 65 e0) FLDENV_MEMmem28 (READ_OP (ADDR_32 DWORD (SEGMENT SS_BASE) EBP - 0x20))))`
 - [ ] `(X86 40e348 3 (BYTES d9 75 e0) FNSTENV_MEMmem28 (WRITE_OP (ADDR_32 DWORD (SEGMENT SS_BASE) EBP - 0x20))))`
 - [ ] `(X86 40661d 4 (BYTES c5 f1 ef c9) VPXOR_XMMdq_XMMdq_XMMdq (WRITE_OP (REG_128 XMM1)) (READ_OP (REG_128 XMM1)) (READ_OP (REG_128 XMM1)))`
 - [ ] `(X86 406626 4 (BYTES c5 f5 75 01) VPCMPEQW_YMMqq_YMMqq_MEMqq (WRITE_OP (REG_256 YMM0)) (READ_OP (REG_256 YMM1)) (READ_OP (ADDR_32 DWORD (SEGMENT DS_BASE) ECX))))`
 - [ ] `(X86 406651 3 (BYTES c5 f8 77) VZEROUPPER)`
 - [ ] `(X86 40e5f8 4 (BYTES 66 0f 15 c0) UNPCKHPD_XMMpd_XMMq (WRITE_OP (REG_128 XMM0)) (READ_OP (REG_128 XMM0)) (READ_OP (REG_128 XMM0)))`
 - [ ] `(X86 4064cd 4 (BYTES c5 f5 74 01) VPCMPEQB_YMMqq_YMMqq_MEMqq (WRITE_OP (REG_256 YMM0)) (READ_OP (REG_256 YMM1)) (READ_OP (ADDR_32 DWORD (SEGMENT DS_BASE) ECX))))`

**Comment by perks** [comment]
`(X86 410bda 3 (BYTES 0f 16 db) MOVLHPS_XMMq_XMMq (WRITE_OP (REG_128 XMM3)) (READ_OP (REG_128 XMM3)))` #135

**Comment by mike-myers-tob** [comment]
`SQRTSS` should work now, in the `issue_127_Missing_X86_Instructions` branch.

**Comment by mike-myers-tob** [comment]
`UNPCKHPD` should work now, in the `issue_127_Missing_X86_Instructions` branch.

**Comment by mike-myers-tob** [comment]
These have all been implemented, with the exception of `FLDENV` which we are tracking under issue #45.
