### ISSUE TITLE
Support for LLVM 5.0

### ISSUE THREAD

**Issue by mewmew** [trailofbits/remill#139]
With the [release of LLVM 5.0](http://releases.llvm.org/5.0.0/docs/ReleaseNotes.html), getting remill (and MC-Semantics) in sync would be lovely. Is this work tracked in a development branch somewhere?

Cheers /u

**Comment by pgoodman** [comment]
The prerequisite is producing a cxx-common build for the LLVM 5.0 toolchain. If I remember later tonight then I'll kick one off for Ubuntu 16.04. For non-Ubuntu I am not sure. @alessandrogario may have some ideas

**Comment by pgoodman** [comment]
I am working on this. I have the build working for Ubuntu 16.04, but tests are failing.

**Comment by mike-myers-tob** [comment]
@alessandrogario got cxx-common to build for the LLVM 5 toolchain right? What's next for addressing this issue?

**Comment by alessandrogario** [comment]
Yes, cxx-common should be compatible with LLVM 5. I'm not sure which tests are failing in remill, but the mcsema tests were working fine (maybe because they are using simple instructions?)

**Comment by pgoodman** [comment]
I have updated cxx-common with the LLVM 5.0 release version number, and uploaded a corresponding Ubuntu 16.04 llvm 5.0 package to s3.

I have tested with another project, and the results are mostly positive. @kumarak is there a way for you to run HART's apache tests using an llvm 5.0 build? That would give me more confidence.

**Comment by kumarak** [comment]
I tested the Apache with HART test suites, and it looked fine. There was also no issue with the OpenSSH binaries.

**Comment by pgoodman** [comment]
OK I'd say that we "support it" then. @alessandrogario can you make a package for ubuntu 14.04? I've already got the 16.04 one made and uploaded.
