### ISSUE TITLE
atomics supported at remill intrinsic level

### ISSUE THREAD

**Issue by hugin** [trailofbits/remill#157]
Needed as part of https://github.com/trailofbits/mcsema/milestone/7.

**Comment by pgoodman** [comment]
Just to expand on this, right now, atomic read-modify-write instructions are not actually atomic in the semantics. For example, `cmpxchg` is reads and separately writes memory: https://github.com/trailofbits/remill/blob/master/remill/Arch/X86/Semantics/SEMAPHORE.cpp

The atomicity constraints are "enforced" by calling `__remill_atomic_begin` before the semantics function, and `__remill_atomic_end` after it, thereby bracketing it in this abstract notion of atomicity. When compiling this bitcode code back to machine code, these intrinsics are elided and lose their meaning, and so we actually lose the atomicity of the original instruction.
