### ISSUE TITLE
Wrong DataLayout for Windows x86 and x64

### ISSUE THREAD

**Issue by pgarba** [trailofbits/remill#183]
The DataLayout is wrong for WIndows x86 and x64. The DataLayout triggers and assert in the MachineFunction::init() (CodeGen) method in LLVM:

assert(Target.isCompatibleDataLayout(getDataLayout()) &&
         "Can't create a MachineFunction using a Module with a "
         "Target-incompatible DataLayout attached\n");

It will be triggered when you try to use ORCJit or MCJIT and the programm will crash.

The Datalayout should be:

Windows x86:
dl = "e-m:x-p:32:32-i64:64-f80:32-n8:16:32-a:0:32-S32";

Windows x64:
dl = "e-m:w-i64:64-f80:128-n8:16:32:64-S128";

Peter

**Comment by artemdinaburg** [comment]
Confirming both of those are correct for clang 4.0 executed via `clang-cl` on Windows.
