### ISSUE TITLE
x86 tests not included in test binaries

### ISSUE THREAD

**Issue by ranweiler** [trailofbits/remill#193]
Due to the commit of what I assume was a temporary `#if 0`, CI still builds and runs test _binaries_, but they contain no actual tests, and spuriously pass.

Offending commit [here](https://github.com/trailofbits/remill/commit/85a874197bdd412dfee234e42417388e7e13ccc6#diff-a7040c5acb199d879c5202be2ddaedddL342).

**Comment by mike-myers-tob** [comment]
Ah. Can you believe that? Just call me Mr. Butterfingers.

Thanks for catching that. Fixing it in https://github.com/trailofbits/remill/pull/194
