### ISSUE TITLE
False positives in tests

### ISSUE THREAD

**Issue by ranweiler** [trailofbits/remill#205]
## Repro

Pick a semantic def for an instruction (whose tests pass!) and make it equivalent to a nop. Example: https://github.com/ranweiler/remill/commit/779b4ec3e239d84282571674804d1fa8c66b1358

## Expected

In the above case, I would (at a minimum) expect the tests in `tests/X86/DATAXFER/MOVD.S` to fail. I would also expect a failure from any other test which implicitly tests the correctness of the `movd` instruction.

## Observed

No tests fail at all, either locally (64-bit Linux 4.14) or in CI, though they seem to be run. See the Travis job log here: https://travis-ci.org/ranweiler/remill/builds/319817422

## Note

I initially observed this when trying to add an initial failing test case for some x87 instructions, and at first thought the scope of this issue might be limited to the test harness's comparisons of native/lifted FPU state (my first repro was after making `fild` a nop). However, it seems to be a broader issue.

**Comment by pgoodman** [comment]
Semantics are built using a special CMake macro, which internally uses the custom `BC` (bitcode) language. Some recent versions of CMake introduced a bug with new languages, where things like `#include` dependencies were not correctly identified. Therefore, when you modify a semantics file, CMake might not actually detect that it needs to rebuild the semantics. Our kludge for this is to manually `touch` the `Instructions.cpp` file. For example, `touch remill/Arch/X86/Runtime/Instructions.cpp`, then `make`, `make build_x86_tests`, `make test`.

**Comment by ranweiler** [comment]
@pgoodman thanks, good to know!

Would that impact CI, though? Also, I'm using Docker for my local build environment (so the build scripts can continue to assume an Ubuntu environment), thus I'm typically rebuilding from scratch (so my "modified" semantics file is actually the only one the build environment has seen). I think either of those should rule out the stale `#include` gotcha in this case.

**Comment by pgoodman** [comment]
I have not observer this affecting Travis because Remill is fully rebuilt on every push/pull/whatever.

**Comment by ranweiler** [comment]
@pgoodman cool, that's my expectation.

To test that there really might be something wrong beyond just my environment, I did the following before opening this issue:
1. Made a branch with this commit: https://github.com/ranweiler/remill/compare/723287871e6a...779b4ec3e239
1. Pushed the branch to my GitHub account with Travis set up to run tests (to control for my local environment). The result of that test run is what I linked to above ([here](https://travis-ci.org/ranweiler/remill/builds/319817422)).

My expectation is that the commit above would make the Remill semantics of `movd` like a `nop`, and so a bunch of tests should fail (any test that counts on lifted `movd` to do something).

A few possibilities:
- My attempt to force a failure (via the above commit) doesn't do what I think it does
- Something is wrong with both CI test running and my local environment, but not generally 
- Something is generally wrong with the test runner

I've successfully run the tests (which I expect to fail) on both the Docker image on which I build everything, and on my Linux 14.4 host machine, not inside of Docker (after copying the freshly-built project into a temporary directory).

I'm very much orienting myself and validating my build environment, so my guess right now is that my expectation is wrong, but otherwise I'm curious if someone else with a known good environment can repro. If my expectation _is_ wrong, it would be useful to know a good way to elicit a nontrivial test failure, but I can ask about that elsewhere.

**Comment by ranweiler** [comment]
Another commit and test build I expect to fail:
- Commit: https://github.com/ranweiler/remill/commit/ca69784b5a679fcc05a6d81c5102063f4bc37916
- Build: https://travis-ci.org/ranweiler/remill/builds/319979010

I notice than when attempting to run the test executables with gdb or strace (containerized or not), I get a ton of `SIGILL`s which are caught by `HandleUnsupportedInstruction` in `tests/X86/Run.cpp`. I would expect (well, _want_) that to cause each test case to fail, but it seems like they are spuriously succeeding.

The SIGILLs might be a sign my test executables are being built incorrectly, which could certainly be caused by my build environment. However, I still expect to see a test failures in Travis. In a little bit I'm probably going to set up a virtualization build env instead of Docker (I'll need to do that for aarch64 anyway), and compare.

**Comment by mike-myers-tob** [comment]
I have seen the `SIGILL`s too, to the extent that I was telling GDB `handle SIGILL nostop noprint` so it would just get to my tests.

I've reproduced what @ranweiler noticed. Something is just passing tests no matter what the semantic is doing. It must be a recent regression but we'll start looking for it.

**Comment by mike-myers-tob** [comment]
It looks like last week's change to `Tests.S` introduced this test runner bug. 

https://github.com/trailofbits/remill/commit/d94d09efd6d2cecf1889fd6bf51890390981c587#diff-a7040c5acb199d879c5202be2ddaeddd

**Comment by ranweiler** [comment]
Ah, yep @mike-myers-tob , I believe [this](https://github.com/trailofbits/remill/commit/d94d09efd6d2cecf1889fd6bf51890390981c587#diff-a7040c5acb199d879c5202be2ddaedddR296) is the illegal instruction: `mov cs, rax`.

Per the Intel SDM (Vol. 1, 3.4.2):
> The CS register cannot be loaded explicitly by an application program. Instead, it is loaded implicitly by instructions or internal processor operations that change program control (such as, procedure calls, interrupt handling, or task switching).

I confirmed that a `mov` into `CS` triggers a SIGILL on a minimal asm executable.

If I remove the attempted save/restore of `CS` around the `DoInvokeTestCase` call in `tests/X86/Tests.S`, I can trigger _exactly_ the test failures and successes I'd expect to trigger via commenting out the bodies of Remill semantic defs. But, when I run _all_ the tests, I get failures in the FMA instructions; I'm not sure if those are standing issues that are unrelated, or were the failing tests alluded to in the commit that @mike-myers-tob linked to above.

**Comment by pgoodman** [comment]
I think the solution to this is pretty straightforward. The Test.S file should not be attempting to save/restore/change the `CS` segment selector. Instead, the various segment selectors should be saved into the `State` struct, by modifying this file: https://github.com/trailofbits/remill/blob/master/tests/X86/PrintSaveState.cpp  and then running the script https://github.com/trailofbits/remill/blob/master/scripts/x86/print_save_state_asm.sh

**Comment by ranweiler** [comment]
@pgoodman cool! I'll go ahead and open a PR for that.
