### ISSUE TITLE
Add support for producing semantics in other IRs

### ISSUE THREAD

**Issue by jrmuizel** [trailofbits/remill#218]
It would make remill more widely useful if it was possible to get instruction semantics without having to rely on lifting from llvm IR. While LLVM IR is nice because of it's wide support, it's not an ideal IR for representing instruction semantics and has poor performance compared to IRs like [cretonne's](https://github.com/stoklund/cretonne).

It seems like it wouldn't be too much work to port the existing C++ code to use [Reactor](https://swiftshader.googlesource.com/SwiftShader/+/HEAD/docs/Reactor.md) or something like it. This would allow either direct compilation to llvm IR, runtime generation of llvm IR, or runtime generation of some other IR like radare's ESIL or binaryninja's LLIL.

**Comment by pgoodman** [comment]
Can you elaborate on your specific use case, or the problems you are facing? What are the ideal features that you are looking for in an IR?

**Comment by jrmuizel** [comment]
There are a couple of specific use cases I'm thinking of:

1. Doing Generic Value-Set analysis for jump table detection as described here: https://binary.ninja/2017/11/06/architecture-agnostic-function-detection-in-binaries.html
2. Replacing the code here: https://github.com/yegord/snowman/blob/master/src/nc/arch/x86/X86InstructionAnalyzer.cpp
3. Replacing the code here: https://github.com/das-labor/panopticon/blob/master/amd64/src/semantic.rs

There's nothing specific about these IRs that I'm looking at (I didn't design them so I don't know the rationale for the author's choices to not use LLVM IR). My request is more about being to interoperate with a given IR without having to make a trip through LLVM IR to get there.

**Comment by pgoodman** [comment]
I'm closing this out for now. It's a pretty intense ask, and going through LLVM is what would enable the best set of optimizations in the first place, I think.
