### ISSUE TITLE
Link with remill

### ISSUE THREAD

**Issue by tathanhdinh** [trailofbits/remill#234]
I have followed the steps in [README](https://github.com/trailofbits/remill/blob/master/README.md) and built `remill` successfully. But I still cannot compile anything with `remill`, concretely I try to compile [Lift.cpp](https://github.com/trailofbits/remill/blob/master/tests/AArch64/Lift.cpp) using:

`clang++- -std=c++11 tests/AArch64/Lift.cpp (llvm-config --cxxflags)`

and got, beside tons of error messages:

```
...
...remill/tests/AArch64/Lift.cpp:177: undefined reference to `remill::GetOSName(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)'
...remill/tests/AArch64/Lift.cpp:178: undefined reference to `remill::Arch::Get(remill::OSName, remill::ArchName)'
...
```

I still cannot figure out which library to be linked here since the built seems do not generate any library (it generates only two executables `remill-clang-4.0`, `remill-llvm-link-4.0` and some bitcode files).

**Comment by tathanhdinh** [comment]
I found it!!!. It should be linked with `libremill.a`.

**Comment by pgoodman** [comment]
What you were really looking for was `make build_x86_tests` on x86, and `make build_aarch64_tests` on aarch64.
