### ISSUE TITLE
build.sh fails due to the broken link

### ISSUE THREAD

**Issue by vadimkotov** [trailofbits/remill#236]
`[x] Failed to download the required dependencies
[-] Library version is libraries-llvm40--amd64
--2018-03-09 14:19:46--  https://s3.amazonaws.com/cxx-common/libraries-llvm40--amd64.tar.gz
Resolving s3.amazonaws.com (s3.amazonaws.com)... 54.231.49.164
Connecting to s3.amazonaws.com (s3.amazonaws.com)|54.231.49.164|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2018-03-09 14:19:47 ERROR 404: Not Found.`

**Comment by alessandrogario** [comment]
Hey @vadimkotov! This is happening because the script is failing to detect your operating system; what system are you compiling this on? Note that we only have tarballs for Ubuntu 14.04 and Ubuntu 16.04.

Here are the links:
https://s3.amazonaws.com/cxx-common/libraries-llvm40-osx-amd64.tar.gz
https://s3.amazonaws.com/cxx-common/libraries-llvm40-ubuntu1604-amd64.tar.gz

**Comment by vadimkotov** [comment]
Hi @alessandrogario! Thanks for the quick reply. This explains that mysterious double-hyphen in the file name :)
I'm running Debian 9 and the good news is that once I manually specified LIBRARY_NAME it did build. The bad news is that mcsema-disass fails:
`
$ mcsema-disass --disassembler ~/ida-7.1/ida64 --os linux --arch amd64 --output true.cfg --binary true --entrypoint main --log_file true.log 
QXcbConnection: Could not connect to display 
Aborted
Traceback (most recent call last):
  File "/home/vadim/tools/mcsema-ve/local/lib/python2.7/site-packages/mcsema_disass-2.0-py2.7.egg/mcsema_disass/ida/disass.py", line 72, in execute
    cwd=os.path.dirname(__file__))
  File "/usr/lib/python2.7/subprocess.py", line 186, in check_call
    raise CalledProcessError(retcode, cmd)
CalledProcessError: Command '/home/vadim/ida-7.1/ida64 -B -S"/home/vadim/tools/mcsema-ve/local/lib/python2.7/site-packages/mcsema_disass-2.0-py2.7.egg/mcsema_disass/ida/get_cfg.py --output /home/vadim/tools/mcsema-ve/remill/true.cfg --log_file /home/vadim/tools/mcsema-ve/remill/true.log --arch amd64 --os linux --entrypoint main" /tmp/tmpKXsmNw/true' returned non-zero exit status 134
Could not generate a CFG. Try using the --log_file option to see an error log.
Traceback (most recent call last):
  File "/home/vadim/tools/mcsema-ve/bin/mcsema-disass", line 11, in <module>
    load_entry_point('mcsema-disass==2.0', 'console_scripts', 'mcsema-disass')()
  File "/home/vadim/tools/mcsema-ve/local/lib/python2.7/site-packages/mcsema_disass-2.0-py2.7.egg/mcsema_disass/__main__.py", line 167, in main
    if 0 == os.path.getsize(args.output):
  File "/home/vadim/tools/mcsema-ve/lib/python2.7/genericpath.py", line 57, in getsize
    return os.stat(filename).st_size
OSError: [Errno 2] No such file or directory: '/home/vadim/tools/mcsema-ve/remill/true.cfg'
`
The log file is empty, but from the output it appears that the CFG generation part is failing. I tried running that IDA command separately and it did produce the log file this time with the following contents:

`
Debugging is enabled.
Loading Standard Definitions file: /home/vadim/tools/mcsema-ve/local/lib/python2.7/site-packages/mcsema_disass-2.0-py2.7.egg/mcsema_disass/defs/linux.txt
`

It did generate the empty .cfg file and I also see *.id*, .nam and .til files which means IDA didn't quit gracefully. 

Anyways, I thought I'd share it in case this is something very common, and you'd what I'm doing wrong. I have a strong suspicion that because I'm running it from inside virtualenv some extra steps should be taken to make IDA happy.

Cheers!

**Comment by artemdinaburg** [comment]
Hi,

Try using  `~/ida-7.1/idal64` (note the l in idal) as the disassembler, it shouldn't try to start QT.

Artem

**Comment by vadimkotov** [comment]
Sadly that didn't work either, because it lacked libncruses, an attempt to install which resulted in a dependency error. I ended up removing i386 arch altogether. Will try setting thigs up using Ubuntu Docker or even a VM. 

Thanks!
