### ISSUE TITLE
Remove remill::Instruction::operand_size

### ISSUE THREAD

**Issue by pgoodman** [trailofbits/remill#247]
It does not seem to be used, and it is also not initialized by the AArch64 decoder, making it less useful.

**Comment by jacwil** [comment]
What about the below reference in DecodeImmediate(), [Arch.cpp:482](https://github.com/trailofbits/remill/blob/master/remill/Arch/X86/Arch.cpp#L482)?

Apologies if this was a stupid question. I haven't done anything more than build and run the unit tests. I'm just beginning to poke around the codebase.

I'm not familiar with C++ in Linux so maybe my first step is to verify my assumption that `CHECK` is just an assert.

```cpp
// Decode an immediate constant.
static void DecodeImmediate(Instruction &inst,
                            const xed_decoded_inst_t *xedd,
                            xed_operand_enum_t op_name) {
  auto val = 0ULL;
  auto is_signed = false;
  auto imm_size = xed_decoded_inst_get_immediate_width_bits(xedd);

  CHECK(imm_size <= inst.operand_size)
      << "Immediate size is greater than effective operand size at "
      << std::hex << inst.pc << ".";
```

**Comment by pgoodman** [comment]
Yes `CHECK` is like an `assert`. I think we should still remove the field, and instead just compute the value in this function (if reasonable) in order to do this check.
