### ISSUE TITLE
Control registers

### ISSUE THREAD

**Issue by tathanhdinh** [trailofbits/remill#248]
I am now trying to add x86 control registers into remill so that I can lift CR-related instructions. As far as I understand, [struct State](https://github.com/trailofbits/remill/blob/master/remill/Arch/X86/Runtime/State.h#L723) should be modified to contains something likes:
```
struct alignas(16) State final : public ArchState {
  ...
  CR cr;
} __attribute__((packed));
```

where `CR` looks like:

```
struct alignas(8) CR final {
  Reg cr0;
  Reg cr1;
  ...
} __attribute__((packed));
```

but looking into [struct GPR](https://github.com/trailofbits/remill/blob/master/remill/Arch/X86/Runtime/State.h#L658) (and similar structs)

```
struct alignas(8) GPR final {
  volatile uint64_t _0;
  Reg rax;
  volatile uint64_t _1;
  Reg rbx;
  volatile uint64_t _2;
  Reg rcx;
  ...
```

I still do not understand why the fields `volatile uint64_t _0`, `volatile uint64_t _1`, ... are needed ?

**Comment by pgoodman** [comment]
Hah I have been doing this myself. You can find my work on the "random" branch :-) For now I have declared control and debug regs as globals as opposed to part of `State`, as `State` is more akin to being thread-specific. Thoughts?

**Comment by pgoodman** [comment]
Also, the purpose of those additional fields is to prevent load or store coalescing by the LLVM optimizer. I never want an LLVM load/store to touch two logically separate entities, so I separate them by fields that are never used.

**Comment by tathanhdinh** [comment]
That is great!!! Many thanks.
Until your response, I never think of whether these (control and debugs) regs should be separated from `State` or not :) I've managed to modify remill to lift some CR-related instructions but your approach is better. Do you have any plan to support `MSR` (Model Specific Registers)?
Thanks again for your work.

**Comment by pgoodman** [comment]
I am not yet sure. I guess it depends on whether or not the MSRs have well-defined "types." For now, RDMSR and WRMSR are implemented using a synchronous hyper call, where the implementation of that hypercall function would need to go and identify the intended MSR based on the register state. That's kind of like CPUID and RDTSC(P). This puts dealing with specific MSRs squarely beyond the scope of instruction semantics, but nonetheless reachable via the hyper call intrinsic.

**Comment by pgoodman** [comment]
Here's an example of implementing a hyper call: https://github.com/trailofbits/remill/blob/master/tests/X86/Run.cpp#L294-L341

And the relevant hyper calls:
https://github.com/trailofbits/remill/blob/random/remill/Arch/Runtime/HyperCall.h#L22
