### ISSUE TITLE
Hidden part of segment registers

### ISSUE THREAD

**Issue by tathanhdinh** [trailofbits/remill#251]
Hello all,

This issue is partially concerned with [issue 248](https://github.com/trailofbits/remill/issues/248) where I asked for lifting new instructions, this time is MSR-related instructions.

The `swapgs` instruction swaps the `GS.base`  with `IA32_KERNEL_GS_BASE` MSR. While the read/write on this MSR is modelled using hypercall, the `GS.base` is located in the hidden part of this segment register; but looking at [`SegmentSelector`](https://github.com/trailofbits/remill/blob/master/remill/Arch/X86/Runtime/State.h#L77), I find that the hidden part of a segment selector is not modelled.

Do you have any plan to support this? Thanks in advance.

**Comment by pgoodman** [comment]
This goes hand-in-hand with support the global and local descriptor tables, and therefore modelling the hidden components of all other segments.

I would gladly accept PRs that move in this direction. I think the right way to implement the `swapgs` semantics is a hyper call.

I'm available on the empire hacking slack if you want to talk more about this and modelling more
ring-0 instructions.
