### ISSUE TITLE
Parity flag in multiplication

### ISSUE THREAD

**Issue by tathanhdinh** [trailofbits/remill#260]
Hello all,

From Intel's manual, `pf` is undefined in both `mul` and `imul` but remill [updates this flag](https://github.com/trailofbits/remill/blob/master/remill/Arch/X86/Semantics/BINARY.cpp#L252) with comment:

```
FLAG_PF = ParityFlag(res); // Technically undefined
```

Could you please explain the reason behind this decision?

**Comment by pgoodman** [comment]
I was probably working based off of a slightly older manual that said it was undefined, but observed that it was being set in a consistent way in actual test cases, so I implemented it.

**Comment by pgoodman** [comment]
That or I went based off of http://sandpile.org/x86/flags.htm

**Comment by tathanhdinh** [comment]
Many thanks!!!
