### ISSUE TITLE
Separated address spaces for State and Memory

### ISSUE THREAD

**Issue by tathanhdinh** [trailofbits/remill#266]
Hello all,

I am trying to introduce the notion of pointer's `addrspace` for `Memory` and `State`. The motivation is that: `remill` allows us to define (via intrinsics functions) a memory model ourselves, but this memory is required to be [conceptually separated](https://github.com/trailofbits/remill/blob/master/docs/LIFE_OF_AN_INSTRUCTION.md#the-remill-runtime-exposed) from state. Moreover, in using `remill` as a [bit-code generator](https://github.com/trailofbits/remill/blob/master/docs/DESIGN.md#runtime) of an emulator, we need a notion to separate `State` from the memory of the emulator.

I use the following example to explain, given the `x86` asm code

```
mov bx, ax
mov [rcx + 0x2], rbx
```

I've used the attribute `addrspace(2)`  for `Memory` to express that `Memory` and `State` (which is on `addrspace(0)` by default) are located at different address spaces, and managed to use `remill` to generate the following bit-code:

```
define %struct.Memory addrspace(2)* @func(%struct.State* noalias, i64, %struct.Memory addrspace(2)* noalias ) {
  %PC = getelementptr inbounds %struct.State, %struct.State* %0, i64 0, i32 6, i32 33, i32 0, i32 0
  %RCX = getelementptr inbounds %struct.State, %struct.State* %0, i64 0, i32 6, i32 5, i32 0, i32 0
  %RBX = getelementptr inbounds %struct.State, %struct.State* %0, i64 0, i32 6, i32 3, i32 0, i32 0
  %4 = getelementptr inbounds %struct.State, %struct.State* %0, i64 0, i32 6, i32 3, i32 0

;mov bx, ax  
  %BX = bitcast %union.anon* %4 to i16*
  %5 = getelementptr inbounds %struct.State, %struct.State* %0, i64 0, i32 6, i32 1, i32 0
  %AX = bitcast %union.anon* %5 to i16*
  %6 = load i16, i16* %AX, align 2
  store i16 %6, i16* %BX, align 2

;mov [rcx + 0x2], rbx
  %7 = load i64, i64* %RCX, align 8
  %8 = add i64 %7, 2
  %9 = load i64, i64* %RBX, align 8
  %10 = add i64 %1, 7
  store i64 %10, i64* %PC, align 8
  %11 = bitcast %struct.Memory addrspace(2)* %2 to i8 addrspace(2)*
  %12 = getelementptr inbounds i8, i8 addrspace(2)* %11, i64 %8
  %13 = bitcast i8 addrspace(2)* %12 to i64 addrspace(2)*
  store i64 %9, i64 addrspace(2)* %13, align 8
  
  ret %struct.Memory addrspace(2)* %2
}
```

The advantage of using explicit address space is that we can easily detect the accesses on `Memory` and `State`, e.g. the store on `bx`:

```
store i16 %6, i16* %BX, align 2
```
is obviously distinguished from the store on [rbx + 0x2]:

```
store i64 %9, i64 addrspace(2)* %13, align 8
```
since the former is on `addrspace(0)` (by default) while the latter on `addrspace(2)`. Programmatically, `getAddressSpace` of the pointer type returns which address space we are accessing.

Because of this motivation, I try to modify `remill` to use explicit address spaces for `State` and `Memory`. I've somehow managed to add explicit address for `Memory`, just insert:

```
#define _AS1 __attribute__((address_space(1)))
#define _AS2 __attribute__((address_space(2)))

#define Memory _AS2 Memory
// #define State _AS1 State
```
at the beginning of `remill/Arch/Runtime/Operators.h`, `remill/Arch/X86/Runtime/Operators.h`, etc. But for `State`, it is not as easy since it relates to almost all functions of `remill` which do not use explicit address space :(

Would you bother to add address space into `remill`? (it is not really a purpose of `remill` then maybe not, but if yes I am happy to make a PR for the case of `Memory`) or do you know how to add explicit address for `State`?

Many thanks in advance for any help.

**Comment by pgoodman** [comment]
In McSema, one of the last things we do is rewrite most `__remill_memory_*` intrinsics to instead use plain old loads/stores [1].

Given that the default load/stores use address space zero, I'd be interested in a PR that moves and generalizes the memory intrinsic lowering code to Remill, where you tell it what address space to use, and it will generate loads/stores for that address space. Then the `Memory *` becomes mostly redundant, which is fine.

Does this sound reasonable?

[1] https://github.com/trailofbits/mcsema/blob/master/mcsema/BC/Optimize.cpp#L214-L340

**Comment by tathanhdinh** [comment]
Many thanks @pgoodman,

I did not even notice the existence of the optimization part that you have shown. That seems a very good entry point for me, I will try to understand it and come back.

Thanks again for the speedy reply.
