### ISSUE TITLE
Floating point instruction lifting

### ISSUE THREAD

**Issue by tathanhdinh** [trailofbits/remill#270]
Hello all,

Using remill to lift the following x86 floating point instruction:

```
db 2d 9f 00 00 00       fld	xword ptr [rip + 0x9f]
```

(which means reading 10 bytes from memory to the FPU register `st0`), I've received the following result (irrelevant LLVM instructions are removed):

```
...
%5 = load i64, i64* %PC
%6 = add i64 %5, 229
...
%13 = call double @__remill_read_memory_f80(%struct.Memory* %2, i64 %6)
%14 = bitcast double %13 to i64
...
```

I still do not understand the result, why there is only a double (i.e. 8 bytes) read from memory (there is no other `__remill_read_memory_*` intrinsics in lifted code).

Many thanks for any response.

**Comment by pgoodman** [comment]
Hi @tathanhdinh, Remill models 80-bit floats as `double`s, as that is more portable for bitcode analysis. The idea is that `__remill_read_memory_f80` (and `__remill_write_memory_f80`) both read/write 10 bytes of memory, and hide the conversion of an 80-bit to a 64-bit float (or vice versa). If you want to model them as actual 80-bit floats then you will need to alter the `State` structure to store them as `long double`s.

**Comment by pgoodman** [comment]
Another relevant difference between Remill bitcode and the x87 FPU is that Remill does not embed the MMX registers inside of the FPU stack registers.

**Comment by tathanhdinh** [comment]
@pgoodman many thanks for the prompted response (as always). What you means in the first response might be inversed? In fact `fld` (in this case) reads only 8 bytes from memory, then the result is converted to a "double extended" 80 bits value?

**Comment by pgoodman** [comment]
The FLD instruction you showed above loads an `xword ptr`. There are `qword ptr` variants, though.

A FLD that loads an 80-bit float from memory will use an intrinsic whose meaning is to load 10 bytes as an 80-bit foot, then internally convert it to a 64-bit float, which is returned.

**Comment by tathanhdinh** [comment]
@pgoodman many thanks for the responses.
