### ISSUE TITLE
Tests for build_x86_tests are failing in Travis

### ISSUE THREAD

**Issue by jacwil** [trailofbits/remill#274]
Tests for `build_x86_tests` are failing

According to [Travis](https://travis-ci.org/trailofbits/remill), test failures started in `build_x86_tests` (llvm40) with merging [bf82eb3](https://github.com/trailofbits/remill/commit/bf82eb39bb73f01dd18efb24489e22627e360f1c) on 2018 June 28.

Tested locally on Ubuntu 16.04 64bit with llvm40 (default), llvm39, and llvm38 have the following test failures:
* `x86`
   * CVTDQ2PDv128m64_0_1
   * CVTDQ2PDv128m64_4_1
   * CMPXCHGm8r8al_3
   * CMPXCHGm16r16ax_3
   * CMPXCHGm32r32eax_3
   * **Error**: `Lifted and native states did not match.`
   * **Error**: `Lifted and native stacks did not match.`
   * **Error**: `Memory access falls outside the valid range of the stack.`

llvm50 has the following test failures:
* `x86`
   * CVTDQ2PDv128m64_0_1
   * CVTDQ2PDv128m64_4_1
   * CMPXCHGm8r8al_3
   * CMPXCHGm16r16ax_3
   * CMPXCHGm32r32eax_3
   * PSHUFDv128v128i8_03_1
   * PSHUFDv128v128i8_47_1
   * PSHUFDv128v128i8_8b_1
   * PSHUFDv128v128i8_cf_1
   * PSLLDQv128v128i8_1
   * **Error**: `Lifted and native states did not match.`
   * **Error**: `Lifted and native stacks did not match.`
   * **Error**: `Memory access falls outside the valid range of the stack.`
* `amd64`
   * CVTPS2DQv128m128_2
   * CVTPS2DQv128v128_2
   * CVTTPS2DQv128m128_2
   * CVTTPS2DQv128v128_2
   * PCMPEQBv128v128_2
   * PCMPEQBv128m128_2
   * PCMPEQWv128v128_2
   * PCMPEQWv128m128_2
   * PCMPEQDv128v128_2
   * PCMPEQDv128m128_2
   * PSHUFDv128v128i8_03_1
   * PSHUFDv128v128i8_47_1
   * PSHUFDv128v128i8_8b_1
   * PSHUFDv128v128i8_cf_1
   * PSLLDQv128v128i8_1
   * **Error**: `Lifted and native states did not match.`

**Comment by jacwil** [comment]
Additional errors in llvm50 tests appear to be prior to merging [bf82eb3](https://github.com/trailofbits/remill/commit/bf82eb39bb73f01dd18efb24489e22627e360f1c) so LLVM 5.0 support is likely a separate issue.

**Comment by jacwil** [comment]
Issue was introduced when attempting to eliminate the double indirection noted in [Arch.cpp#L423](https://github.com/trailofbits/remill/blob/master/remill/Arch/Arch.cpp#L423). Commenting out the removal of the alloca instruction in [Arch.cpp#L460-L475](https://github.com/trailofbits/remill/blob/master/remill/Arch/Arch.cpp#L460-L475) fixes the tests.

Note that `make build_x86_tests` will no longer compile with the change above unless you revert [Lifter.cpp, `LoadRegAddress()`](https://github.com/trailofbits/remill/blob/master/remill/BC/Lifter.cpp#L206) back to:
```cpp
return new llvm::LoadInst(FindVarInFunction(block->getParent(), reg_name), "", block);
```

and [Util.cpp, `LoadProgramCounterRef()`](https://github.com/trailofbits/remill/blob/master/remill/BC/Util.cpp#L192) back to:
```cpp
llvm::IRBuilder<> ir(block);
return ir.CreateLoad(FindVarInFunction(block->getParent(), "PC"));
```
and setting `cond` in [Util.cpp, `LoadBranchTaken()`](https://github.com/trailofbits/remill/blob/master/remill/BC/Util.cpp#L219) back to:
```cpp
auto cond = ir.CreateLoad(
    ir.CreateLoad(FindVarInFunction(block->getParent(), "BRANCH_TAKEN")));
```

This is not a proposal to comment out or revert the elimination of the double indirection. It is only meant to highlight where the source of the test failures are so it can be addressed accordingly.

**Comment by pgoodman** [comment]
This is fixed in Linux.
