### ISSUE TITLE
CR and DR are removed from basic block

### ISSUE THREAD

**Issue by tathanhdinh** [trailofbits/remill#285]
@pgoodman  In the commit #276, you have removed [DR](https://github.com/trailofbits/remill/commit/71b24d6cf031ba98bf0225aee278cb2f0dee7240#diff-60224a87f885f42d948230c9ec9351ddL30) and [CR](https://github.com/trailofbits/remill/commit/71b24d6cf031ba98bf0225aee278cb2f0dee7240#diff-60224a87f885f42d948230c9ec9351ddL40) from basic block.

Now, how we can lifting instructions accessing these registers? Because [this check](https://github.com/trailofbits/remill/commit/71b24d6cf031ba98bf0225aee278cb2f0dee7240#diff-cc2c1f23701c1aa7eb1c9bf42cb78cd1R152) always fails.

**Comment by pgoodman** [comment]
This check should always pass: https://github.com/trailofbits/remill/commit/71b24d6cf031ba98bf0225aee278cb2f0dee7240#diff-cc2c1f23701c1aa7eb1c9bf42cb78cd1R147

If it's not, then try adding `[[gnu::used]]` to the renamed variables and see if that helps. If it does, please submit a PR.

**Comment by tathanhdinh** [comment]
Hi @pgoodman 

Unfortunately adding [[gnu::used]] doesn't work for me :(

I believe that the extern global variable will be [stripped off](https://stackoverflow.com/questions/23668247/gcc-warning-used-attribute-ignored) from the module if it is not referenced anywhere. A very simple example is that:

```
__attribute__((__used__)) extern int a;

int func() {
	return 1;
}
```

then 

```
clang -c -emit-llvm extern.c -o extern.bc
extern.c:1:16: warning: 'used' attribute ignored [-Wignored-attributes]
__attribute__((__used__)) extern int a;
```

and we can see that there is no `exernal global` for `a`

```
; ModuleID = 'extern.bc'
source_filename = "extern.c"
target datalayout = "e-m:e-i64:64-f80:128-n8:16:32:64-S128"
target triple = "x86_64-unknown-linux-gnu"

; Function Attrs: noinline nounwind optnone uwtable
define i32 @func() #0 {
  ret i32 1
}

attributes #0 = { noinline nounwind optnone uwtable "correctly-rounded-divide-sqrt-fp-math"="false" "disable-tail-calls"="false" "less-precise-fpmad"="false" "no-frame-pointer-elim"="true" "no-frame-pointer-elim-non-leaf" "no-infs-fp-math"="false" "no-jump-tables"="false" "no-nans-fp-math"="false" "no-signed-zeros-fp-math"="false" "no-trapping-math"="false" "stack-protector-buffer-size"="8" "target-cpu"="x86-64" "target-features"="+fxsr,+mmx,+sse,+sse2,+x87" "unsafe-fp-math"="false" "use-soft-float"="false" }

!llvm.module.flags = !{!0}
!llvm.ident = !{!1}

!0 = !{i32 1, !"wchar_size", i32 4}
!1 = !{!"clang version 5.0.2 (tags/RELEASE_502/final)"}
```

**Comment by pgoodman** [comment]
What happens if you do:

```c++
(void) CR0;
(void) CR1;
...
```

inside of `__remill_basic_block`?

**Comment by pgoodman** [comment]
See #286

**Comment by tathanhdinh** [comment]
Another approach #287

**Comment by pgoodman** [comment]
Merged your PR.
