### ISSUE TITLE
Reading control register

### ISSUE THREAD

**Issue by tathanhdinh** [trailofbits/remill#309]
Hello all,

Using remill to lift a `mov` from control registers, e.g.

```
44 0f 20 c0       mov rax, cr8
```

I get a crash, e.g. using the [lifting tool](https://github.com/trailofbits/remill/tree/master/tools/lift)

```
./tools/lift/remill-lift-6.0 --bytes 440f20c0 --ir-out /dev/stdout
F0926 16:04:50.313108 19121 Lifter.cpp:415] Unable to convert value   %370 = load %union.anon, %union.anon* @CR8 to intended argument type i64 for operand (READ_OP (REG_64 CR8)) of instruction (AMD64 0 4 (BYTES 44 0f 20 c0) MOV_CR_GPR64_CR (WRITE_OP (REG_64 RAX)) (READ_OP (REG_64 CR8)))
*** Check failure stack trace: ***
    @           0x44fe9d  google::LogMessage::Fail()
    @           0x451f34  google::LogMessage::SendToLog()
    @           0x44f9cd  google::LogMessage::Flush()
    @           0x452899  google::LogMessageFatal::~LogMessageFatal()
    @           0x4730b4  remill::(anonymous namespace)::ConvertToIntendedType()
fish: Tâche -1283777104, './tools/lift/remill-lift-6.0 --…' terminée par le signal SIGABRT (Abandon)
```

The problem comes from converting a union (which represents a control register value, e.g. [cr8](https://github.com/trailofbits/remill/blob/master/remill/Arch/X86/Runtime/State.h#L824))

https://github.com/trailofbits/remill/blob/ec245a115a85bf780d3a19acc7903b30a4c5c456/remill/BC/Lifter.cpp#L400-L405

to an integer value (which is aliased for a register): casting between these types is not valid in LLVM.

I can think of (and have tried) two methods to handle the problem, one (which is indeed previously used by remill) is to use alias for control registers, e.g.

```C++
// remill/Arch/X86/Runtime/BasicBlock.cpp

...
extern CR0Reg gCR0;
// other globals for CRi...
...

Memory *__remill_basic_block(State &state, addr_t curr_pc, Memory *memory) {
    ...
    auto &CR0 = gCR0.flat; // CR0 is aliased by its flat
    // other aliases for CRi...
    ... 
}
```

Another is to slightly modify the type of the semantics function, e.g. from

https://github.com/trailofbits/remill/blob/ec245a115a85bf780d3a19acc7903b30a4c5c456/remill/Arch/X86/Semantics/SYSTEM.cpp#L109

to 

```
DEF_SEM(READ_CONTROL_REG_64, R64W dst, R64W src)
```

(or maybe better we can add a "read-only reference" type, e.g.

```
template <typename T>
struct RnR final {
  const T * const val_ref;
};
...

typedef RnR<uint64_t> R64R;
...
DEF_SEM(READ_CONTROL_REG_64, R64W dst, R64R src)
```

to profit the effect of `Write(dst, Read(src))` where `Read` proceeds now on `R64W` type. For example, by using the later

```
./tools/lift/remill-lift-6.0 --bytes 440f20c0 --ir-out /dev/stdout
...

; Function Attrs: noinline nounwind
define %struct.Memory* @sub_0(%struct.State* noalias dereferenceable(3280), i64, %struct.Memory* noalias) local_unnamed_addr #0 {
  %4 = getelementptr inbounds %struct.State, %struct.State* %0, i64 0, i32 6, i32 33, i32 0, i32 0
  %5 = getelementptr inbounds %struct.State, %struct.State* %0, i64 0, i32 6, i32 1, i32 0, i32 0
  %6 = add i64 %1, 4
  store i64 %6, i64* %4, align 8
  %7 = tail call %struct.Memory* @__remill_sync_hyper_call(%struct.State* nonnull dereferenceable(3280) %0, %struct.Memory* %2, i32 1) #4
  %8 = load i64, i64* getelementptr inbounds (%union.anon, %union.anon* @CR8, i32 0, i32 0), align 8
  store i64 %8, i64* %5, align 8
  %9 = tail call zeroext i8 @__remill_undefined_8() #5
  %10 = getelementptr inbounds %struct.State, %struct.State* %0, i64 0, i32 2, i32 13
  store i8 %9, i8* %10, align 1
  %11 = getelementptr inbounds %struct.State, %struct.State* %0, i64 0, i32 2, i32 9
  store i8 %9, i8* %11, align 1
  %12 = getelementptr inbounds %struct.State, %struct.State* %0, i64 0, i32 2, i32 7
  store i8 %9, i8* %12, align 1
  %13 = getelementptr inbounds %struct.State, %struct.State* %0, i64 0, i32 2, i32 5
  store i8 %9, i8* %13, align 1
  %14 = getelementptr inbounds %struct.State, %struct.State* %0, i64 0, i32 2, i32 3
  store i8 %9, i8* %14, align 1
  %15 = getelementptr inbounds %struct.State, %struct.State* %0, i64 0, i32 2, i32 1
  store i8 %9, i8* %15, align 1
  %16 = load i64, i64* %4, align 8
  %17 = tail call %struct.Memory* @__remill_missing_block(%struct.State* nonnull %0, i64 %16, %struct.Memory* %7)
  ret %struct.Memory* %17
}
...
```

Personally, I prefer the second one because it is sorter (though trickier?), but I have no other strong arguments for this.

Many thanks for any comment.

**Comment by pgoodman** [comment]
Hi @tathanhdinh, did we ever resolve this?

**Comment by tathanhdinh** [comment]
Hi @pgoodman 
Sorry to bother you, just want to ping you a little bit. Could you please review the problem of reading from control register? I will send a PR if you don't mind.
Many thanks.

**Comment by pgoodman** [comment]
@tathanhdinh I updates the variables to revert them back to `gCRn` format. More importantly, though, I think maybe another hypercall is needed. Specifically, right now we've got:

```c++
DEF_SEM(READ_CONTROL_REG_64, R64W dst, R64 src) {
  memory = __remill_sync_hyper_call(
      state, memory, SyncHyperCall::kAssertPrivileged);
  Write(dst, Read(src));
  auto u = __remill_undefined_8();
  Write(FLAG_OF, u);
  Write(FLAG_SF, u);
  Write(FLAG_ZF, u);
  Write(FLAG_AF, u);
  Write(FLAG_PF, u);
  Write(FLAG_CF, u);
  return memory;
}
```

But what I think is missing is, right after the privilege check, anther thing, like:
```c++
  memory = __remill_sync_hyper_call(
      state, memory, SyncHyperCall::kGetCR);
```

We have a corresponding `kSetCR` at the end of the `WRITE_CONTROL_REG_32/64`, and the way I envisioned that is as a kind of synchronization point between the emulator and remill's view of things, i.e. a place where the emulator can inspect `gCR0`, `gCR1`, etc. and then update itself. But maybe we also need something like that for reading control registers. That would also mean that `WRITE_CONTROL_REG_32` would change to begin with a `kGetCR` after the privilege assertion. Thoughts?

**Comment by pgoodman** [comment]
ping @tathanhdinh

**Comment by tathanhdinh** [comment]
@pgoodman Sorry for the late response. I'm quite busy current days. I will come back ASAP.

**Comment by pgoodman** [comment]
@tathanhdinh I have merged the changed code. We can re-open this issue if you think additional hypercalls are warranted.
