### ISSUE TITLE
ARMv7 (AArch32) support

### ISSUE THREAD

**Issue by VelocityRa** [trailofbits/remill#327]
Are there plans to support AArch32?
I did see #310, but there was no comment on whether it's planned.

Thanks!

**Comment by artemdinaburg** [comment]
Maybe @pgoodman can better answer, but to my knowledge there are no active plans for AArch32. We would absolutely love to support ARMv7 though. Is it something you are interested in working on?

**Comment by VelocityRa** [comment]
>there are no active plans for AArch32. We would absolutely love to support ARMv7 though

ARMv7 implements AArch32, doesn't it? It runs A32 and T32 instructions.

I'm interested in Cortex (ARMv7-A) support because [AOT](https://en.wikipedia.org/wiki/Ahead-of-time_compilation) it can be a long term goal of a [PlayStation Vita emulator](https://github.com/Vita3K/Vita3K) I'm working on. It would save us a lot of work if we could use a pre-existing binary lifter.

> Is it something you are interested in working on?

The more immediate possibility for us is adding support to [dynarmic](https://github.com/MerryMage/dynarmic) (JIT) for ARMv7. At the moment we're using unicorn-engine, which is pretty of slow. It would be less work than AOT.

So I probably won't be working on AOT any time soon - in a few years, maybe, when the emulator is more mature.

**Comment by pgoodman** [comment]
@VelocityRa I think AArch32 is almost identical to ARMv7. Besides that, we have no immediate plans to implement ARMv7/AArch32 support. If you or someone else pursues this then we could fund you through bonus-based pull requests, and we could also guide you through what supporting a new architecture "looks like."

**Comment by VelocityRa** [comment]
@pgoodman I see, thank you.
