### ISSUE TITLE
Semaphore instructions lifting

### ISSUE THREAD

**Issue by tathanhdinh** [trailofbits/remill#345]
I still do not understand how the instructions `xadd` (and `lock xadd`) are lifted, currently the lifting function of `xadd` is: https://github.com/trailofbits/remill/blob/054108a945865101896c3310297f23d7e37c46c6/remill/Arch/X86/Semantics/SEMAPHORE.cpp#L93-L109

This function makes me confused, why does it need to use the intrinsic `remill_fetch_and_add`? 

IMHO, it can be implemented using only existing read/write operators. First, `xadd` (or its atomic version `lock xadd`) has always `is_atomic_read_modify_write` as true since it's a semaphore instruction: https://github.com/trailofbits/remill/blob/054108a945865101896c3310297f23d7e37c46c6/remill/Arch/X86/Arch.cpp#L991-L997

then the semantics function is always atomic thanks to the barriers `remill_atomic_begin/end`:

https://github.com/trailofbits/remill/blob/054108a945865101896c3310297f23d7e37c46c6/remill/BC/Lifter.cpp#L140-L146

https://github.com/trailofbits/remill/blob/054108a945865101896c3310297f23d7e37c46c6/remill/BC/Lifter.cpp#L194-L200

So, the function that lifts `xadd` is simply:

```C++
template <typename D1, typename S1, typename D2, typename S2>
DEF_SEM(XADD, D1 dst1, S1 src1, D2 dst2, S2 src2) {
  auto val1 = Read(src1);
  auto val2 = Read(src2);
  auto sum = UAdd(val1, val2);
  WriteZExt(dst2, val1);
  WriteZExt(dst1, sum);
  WriteFlagsAddSub<tag_add>(state, val1, val2, sum);

  return memory;
}
```

I've tested and it passes the test (the generated LLVM code is much simpler than the current version).

I don't understand why the [barriers](https://preshing.com/20120710/memory-barriers-are-like-source-control-operations/) should be used here (do the `remill_atomic_begin/end` take care all the work?). I guess that, for example the instruction `xadd [rax], rbx`, the barriers `LoadLoad` and `StoreStore` should be useful because they prevent reordering load/store operation between threads/processes, but remill seems to use the `StoreLoad` barrier?

I'm very new to synchronization techniques then sorry for my ignorance and many thanks for any response.

**Comment by pgoodman** [comment]
It's a fair question. The semantics as you present them don't cut it when recompiling back to machine code, e.g. in the case of an original binary being multi-threaded, and lifting it with McSema. That is why the `UFetchAdd` [1] is used, which is an atomic memory access intrinsic. The store load barrier is just semantic fluff really, you use case can probably remove/inline those calls. This instruction is likely also to be "wrapped" by calls to atomic begin/end, more semantic fluff.

[1] https://github.com/trailofbits/remill/blob/master/remill/Arch/Runtime/Operators.h#L522

**Comment by pgoodman** [comment]
In your use cases, you can probably lower/implement the fetch/add memory intrinsics in terms of the plain old ones. My guess is you'd end up seeing nearly the same bitcode after doing that.

**Comment by tathanhdinh** [comment]
@pgoodman Thanks a lot for the response.

> The semantics as you present them don't cut it when recompiling back to machine code, e.g. in the case of an original binary being multi-threaded, and lifting it with McSema.

I may understand better, does you mean that, given the StoreLoad barrier has no effect, then the lifted code will have problem, in the following situation, for example: two processes P1/P2 running on different CPUs but accessing to the same memory

```

P1                              P2

v0 = load [rax];
v1 = read rbx;
[rax] = v0 + v1;
rbx = v1                        v0 = load [rax]
                                v1 = read rbx
                                ...
```

without the intrinsic `fetch_and_add` (which is warranted as atomic), then there is no warranty that there is no interleaved operations between these processes?

Is my interpretation correct?

**Comment by pgoodman** [comment]
Yes.

**Comment by pgoodman** [comment]
In theory, things like atomic begin/end ought be implemented in terms of entering/exiting a software or hardware transaction. We don't support failure atomicity (implied by Intel's precise interrupt semantics), so handling data races is left as an exercise for the user of the bitcode. In practice, that's heavy handed, and so we have the atomic memory access intrinsics.

**Comment by tathanhdinh** [comment]
Many thanks @pgoodman.
