### ISSUE TITLE
no use of your hard work, if users can not build!!

### ISSUE THREAD

**Issue by 0x410c** [trailofbits/remill#349]
i am trying to build this library for like 3 days, errors everywhere!!, what is the use of you work if users cannot even build your libraries? if you cannot provide a test build system, at least provide binaries!

**Comment by artemdinaburg** [comment]
What Linux distribution? I tried it just now and it builds fine on Ubuntu 18.04 64-bit. No errors reported during build or installation.

Exact steps below:

```sh
$ mkdir ~/remill-test
$ git branch -v
* master c0c0847 Update build.sh
$ scripts/build.sh --prefix /home/artem/remill-test
<...lots of build output here...>
$ cd remill-build
$ make install
<...lots of install output here...>
$ /home/artem/remill-test/bin/remill-lift-4.0 --version
remill-lift-4.0
```

**Comment by 0x410c** [comment]
windows 10, 1809

**Comment by artemdinaburg** [comment]
Just tried on my Windows 10 install. Follow the directions at: https://github.com/trailofbits/mcsema#on-windows

Some of my build output, to make it easier to debug your issues:
```
C:\Projects\remill>git branch -v
* master c0c0847 Update build.sh

C:\Projects\remill>mkdir remill-build && cd remill-build

C:\Projects\remill\remill-build>"C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Auxiliary\Build\vcvars64.bat"
**********************************************************************
** Visual Studio 2017 Developer Command Prompt v15.0
** Copyright (c) 2017 Microsoft Corporation
**********************************************************************
[vcvarsall.bat] Environment initialized for: 'x64'

C:\Projects\remill\remill-build>cmake -G "Visual Studio 15 2017" -T llvm -A x64 -DCMAKE_BUILD_TYPE=Release -DLIBRARY_REPOSITORY_ROOT=C:\Projects\tob_libraries -DCMAKE_INSTALL_PREFIX=C:\ ..
-- The C compiler identification is Clang 7.0.1
-- The CXX compiler identification is Clang 7.0.1
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/BuildTools/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x64/cl.exe
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/BuildTools/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x64/cl.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/BuildTools/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x64/cl.exe
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/BuildTools/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x64/cl.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Install prefix: C:/
-- The following compiler has been selected to compile the bitcode: C:/Projects/tob_libraries/llvm/bin/clang++.exe
-- The ASM compiler identification is MSVC
-- Found assembler: C:/Program Files (x86)/Microsoft Visual Studio/2017/BuildTools/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x64/cl.exe
 > Generating runtime target: x86
 > Generating runtime target: x86_avx
 > Generating runtime target: x86_avx512
 > Generating runtime target: amd64
 > Generating runtime target: amd64_avx
 > Generating runtime target: amd64_avx512
 > Generating runtime target: aarch64
-- Using LLVM_INSTALL_PREFIX hints for find_package(LLVM): C:/Projects/tob_libraries/llvm/lib/cmake/llvm/;C:/Projects/tob_libraries/llvm/share/llvm/cmake/
-- Disabled ABI libraries: Linux
-- You can change this setting with -DMCSEMA_DISABLED_ABI_LIBRARIES:STRING="Name1;Name2"
-- Skipping ABI library: mcsema/OS/Linux
-- Skipping the Maze example
-- Using LLVM_INSTALL_PREFIX hints for find_package(LLVM): C:/Projects/tob_libraries/llvm/lib/cmake/llvm/;C:/Projects/tob_libraries/llvm/share/llvm/cmake/
-- Configuring done
-- Generating done
-- Build files have been written to: C:/Projects/remill/remill-build

C:\Projects\remill\remill-build>cmake --build . --config Release -j 4
<...lots of build output...>

C:\Projects\remill\remill-build>tools\lift\Release\remill-lift-5.0.exe --version
remill-lift-5.0.exe
```

**Comment by 0x410c** [comment]
"On Windows, only the LLVM 5.0.1 package is supported for building semantics"

here you used 7.0.1, please be specific what to use.

**Comment by artemdinaburg** [comment]
Both. The README covers this.

> There are two versions of LLVM used by remill and mcsema. One version (currently 7.0.1) builds remill and mcsema. Another version (currently 5.0.1) is used to build the translation semantics.

> On Windows, only the LLVM 5.0.1 package is supported for building semantics. If you build it yourself, use the Visual Studio 2017 Win64 generator with the LLVM 5.0.1 toolchain. The cxx-common script will automatically take care of this requirement.


1) Install LLVM 7.0.1
2) 
 ```
cd C:\Projects\remill\scripts\windows (or wherever you cloned remill)
powershell -nologo -executionpolicy bypass -File llvm_toolchain_vs2017.ps1
  ```
3) Get https://s3.amazonaws.com/cxx-common/libraries-llvm50-windows10-amd64.7z and extract it to `C:\Projects\tob_libraries`. This will get you a binary package of LLVM 5.0.1 and some other dependencies that build translation semantics.
4) Continue with Step 4 of the building guide: https://github.com/trailofbits/mcsema#step-4-building

**Comment by 0x410c** [comment]
build succesfully, thank you!, i need to integrate in both x86 and x64 binaries, so

1) how to build x86 binaries?
2) where are the header files?
3) where are the docs?

**Comment by artemdinaburg** [comment]
Hi,

We do not support building x86 binaries at the moment. We very strongly suspect the translation code works only on 64-bit platforms, although admittedly have not actually tested a 32-bit build. If you are trying to translate 32-bit binaries, you can do it with a 64-bit build of remill. In fact, there is cross-arch and cross-os compatibility (that is, you can translate linux bins on windows and vice versa).

Are you able to share what you are trying to do? We can try to point you in the right direction.

**Comment by 0x410c** [comment]
basically i am trying to create a generic deobfuscator for certain malware family, i am considering diffrent approaches, one of which is to feed remill blocks of obfuscated code, get the ir, optimize it with llvm optimizer pass and reconstruct it to x86, although its slow but i think it is the most efficient and fastest way to do it!, as the dynamic cfg generator is in python 32 bit with x64db connected, i would need a 32bit build to use it!

**Comment by artemdinaburg** [comment]
So we do not support building x86 binaries for remill and it doesn't look like we will ever support it. The 64-bit build of remill can of course lift 32-bit x86 code. 

From the description of your problem, you can shell out to a separate 64-bit program that can do the analysis. Or maybe you can use a 64-bit python and a 64-bit remill, if you intend to use it as a library.

**Comment by 0x410c** [comment]
no problems, i will find a work around, thanks for the awesome work!
