### ISSUE TITLE
MMX Instruction support.

### ISSUE THREAD

**Issue by pgoodman** [trailofbits/remill#44]
Implement and test the following MMX instructions:
 - [x] EMMS
 - [x] FEMMS
 - [x] MASKMOVQ
 - [x] MOVD
 - [x] MOVNTQ
 - [x] MOVQ
 - [x] PABSB
 - [x] PABSD
 - [x] PABSW
 - [x] PACKSSDW
 - [x] PACKSSWB
 - [x] PACKUSWB
 - [x] PADDB
 - [x] PADDD
 - [x] PADDQ
 - [x] PADDSB
 - [x] PADDSW
 - [x] PADDUSB
 - [x] PADDUSW
 - [x] PADDW
 - [x] PALIGNR
 - [x] PAND
 - [x] PANDN
 - [x] PAVGB
 - [x] PAVGW
 - [x] PCMPEQB
 - [x] PCMPEQD
 - [x] PCMPEQW
 - [x] PCMPGTB
 - [x] PCMPGTD
 - [x] PCMPGTW
 - [x] PEXTRW
 - [x] PHADDD
 - [x] PHADDSW
 - [x] PHADDW
 - [x] PHSUBD
 - [x] PHSUBSW
 - [x] PHSUBW
 - [x] PINSRW
 - [x] PMADDUBSW
 - [x] PMADDWD
 - [x] PMAXSW
 - [x] PMAXUB
 - [x] PMINSW
 - [x] PMINUB
 - [x] PMOVMSKB
 - [x] PMULHRSW
 - [x] PMULHUW
 - [x] PMULHW
 - [x] PMULLW
 - [x] PMULUDQ
 - [x] POR
 - [x] PSADBW
 - [x] PSHUFB
 - [x] PSHUFW
 - [x] PSIGNB
 - [x] PSIGND
 - [x] PSIGNW
 - [x] PSLLD
 - [x] PSLLQ
 - [x] PSLLW
 - [x] PSRAD
 - [x] PSRAW
 - [x] PSRLD
 - [x] PSRLQ
 - [x] PSRLW
 - [x] PSUBB
 - [x] PSUBD
 - [x] PSUBQ
 - [x] PSUBSB
 - [x] PSUBSW
 - [x] PSUBUSB
 - [x] PSUBUSW
 - [x] PSUBW
 - [x] PUNPCKHBW
 - [x] PUNPCKHDQ
 - [x] PUNPCKHWD
 - [x] PUNPCKLBW
 - [x] PUNPCKLDQ
 - [x] PUNPCKLWD
 - [x] PXOR

**Comment by pgoodman** [comment]
This issue is tracked by branch [issue_44_mmx_support](/trailofbits/remill/tree/issue_44_mmx_support).

**Comment by erhlee-bird** [comment]
Going to join on this issue
