### ISSUE TITLE
Broken build.sh compilation script

### ISSUE THREAD

**Issue by dcdelia** [trailofbits/remill#80]
I got a fresh clone of the repository (c0e7a2e) and build.sh fails when attempting to execute the cmake command. In particular, variables such as CMAKE_C_COMPILER are not being set correctly to point to the downloaded LLVM release:
```
[+] Running cmake
realpath: ./build/llvm: No such file or directory
-- The C compiler identification is unknown
-- The CXX compiler identification is unknown
CMake Error at CMakeLists.txt:5 (project):
  The CMAKE_C_COMPILER:

    /bin/clang

  is not a full path to an existing compiler tool.
[...]
```
I fixed build.sh as follows, temporarily leaving the build directory before invoking realpath:

```
LLVM_DIR=${BUILD_DIR}/$LLVM_DIR
cd ..
LLVM_DIR=$(realpath $LLVM_DIR)
cd -
BINDIR=$LLVM_DIR/bin
```

**Comment by pgoodman** [comment]
@withzombies does this work for you? I know you had realpath issues.

**Comment by withzombies** [comment]
I had the same issues and issued a pull request that you never merged.

**Comment by pgoodman** [comment]
Whoops, merged now. @dcdelia does it work for you now?

**Comment by dcdelia** [comment]
It does, thank you!
