### ISSUE TITLE
Add INVALID_INSTRUCTION instruction

### ISSUE THREAD

**Issue by pgoodman** [trailofbits/remill#92]
This will be and act just like [`INVALID_INSTRUCTION`](https://github.com/trailofbits/remill/blob/master/remill/Arch/X86/Runtime/Instructions.cpp#L117-L127). The purpose will be to gracefully recovery from an instruction decode error. There are three parts to this:

 1. Them "semantics" must be implemented, much like `UNSUPPORTED_INSTRUCTION`. It should invoke a synchronous hypercall, and set up a meaninful hyper call ID.
 2. [This code](https://github.com/trailofbits/remill/blob/master/remill/BC/Lifter.cpp#L697) will need to be modified to look for `instr->category == Instruction::kCategoryInvalid`.
 3. [This code](https://github.com/trailofbits/remill/blob/master/remill/BC/Lifter.cpp#L610) will need to be updated in case the invalid instruction is the last instruction in a block.

**Comment by douggard** [comment]
I see `kInvalid` is already defined in [hypercall.h here](https://github.com/trailofbits/remill/blob/932dd0212dc3e2fdd180698e82172461213b2bca/remill/Arch/Runtime/HyperCall.h#L9). Should that be used as the ID?

The hypercall for `UNSUPPORTED_INSTRUCTION` is defined [here](https://github.com/trailofbits/remill/blob/f1075deac27cb420b805cfd5c452a668d5fea98d/remill/Arch/X86/Runtime/Instructions.cpp#L119), is it fine to define the one for `INVALID_INSTRUCTION` alongside of it? 

What exactly should occur when an invalid instruction is the last in a block?

**Comment by pgoodman** [comment]
`kInvalid` is meant to signal an invalid hypercall. It is necessary to define a new hypercall ID for an invalid instruction. I think `INVALID_INSTRUCTION` should be a bit like `INT3`, where it sets up a hyper call ID and defers to the Lifter to add a terminating tail-call to `__remill_async_hyper_call`. If an invalid instruction appears anywhere in a basic block, then it should be lifted, but then lifting should stop after that point and a tail-call to `instrinsics->async_hyper_call`.

**Comment by pgoodman** [comment]
Merged PR #101
