### ISSUE TITLE
docs: Add documentation of remill Intrinsics

### ISSUE THREAD

**Issue by mewmew** [trailofbits/remill#95]
I understand that the documentation of this project is a work in progress.

Just wanted to open an issue to track the documentation of Intrinsics in remill as they seem to be a key component, referred to from other parts of the docs.

As of today *2017-02-14*, the [Intrinsics.md](https://github.com/trailofbits/remill/blob/master/docs/INTRINSICS.md) document is an empty file, just waiting to receive some love.

**Comment by mike-myers-tob** [comment]
Hey @mewmew you should also see `Operators.md`, I hope these two documents are useful.

**Comment by mewmew** [comment]
Thanks Mike! Read both docs, and there provided some insight. Could you just briefly elaborate what you mean by Remill not modelling memory *access*?

> ..., but it does not model memory *access* behaviors ...

Could you give an example instruction, for which Remill does not model memory access behaviour. I may have misunderstood your description, so perhaps this is not what you meant.
